### PR TITLE
Sexuality: improve discussion of labels and "queer"

### PR DESCRIPTION
**Pull request by jhwgh1968**
- [x] Everything I'm contributing is my own work, used with permission (and attributed as necessary), or is very clearly [fair use](https://en.wikipedia.org/wiki/Fair_use)
- [x] I agree to put my contribution into the Public Domain (or CC-0, if that doesn't apply where you are)

---

I didn't watch the video you linked, but I don't think this undermines it. It also is designed to help with terminology, at least a little bit.

I didn't touch the lower section on the letters, but maybe it can be consolidated or reorganized? I'll let you decide.

### CODE REVIEW

**Comment by VegaDeftwing** [comment]
> [...] bridging and bonding. Bridging is about presenting a collective social consciousness to others, in order to build bonds outside. Bonding is about building bonds within a group and creating a group identity.

Is a bit dense. I think what you mean is Bridging is presenting the community and its ideas to others outside the group, while bonding is about using the shared ideas to strengthen ties within the group, but as you have this written I had to read it like 3 times to get that- I think in part because you used the word "bonds" in the definition of bridging.

I think having examples of each would help.

Similarly, I think more examples of each term and where they fit in the hierarchy-ish system you've described would help

**Comment by jhwgh1968** [comment]
You can tell I am a bit distracted as I've been working on this, heh.

See if this version, which also improves academic rigor and word choice, is clearer.

**Comment by jhwgh1968** [comment]
Good catch. That should clear it up.

**Comment by VegaDeftwing** [comment]
Looks good! Thank you for all the hard work!

**Pull request merged**
