### PR TITLE
Update arch.md

### PR DESCRIPTION
**Pull request by Head-on-a-Stick**
Please delete this shitty "guide" from your site.

It is outdated and error-ridden.

As a regular on the Arch forums I can tell you that half-assed crap like this doesn't help anybody. Please stop.

### CODE REVIEW

**Comment by VegaDeftwing** [comment]
I really appreciate this well thought out and eloquently worded feedback. Unfortunately, I'm going to have to ignore the advice of someone that only knows how to provide negative feedback in a hurtful way and instead recommend that you contribute to the guide instead. There's plenty of pages that could really use the contributions of somebody with as much expertise as you must have, given that you felt so strongly about this :) Thanks

**Comment by VegaDeftwing** [comment]
If you'd like me to delete this page for real @Head-on-a-Stick , then put your ~~money~~ editing skills where your mouth is. I opened a discussion on https://wiki.archlinux.org/title/Talk:Installation_guide which goes into a bit more details about why I felt I needed to write this page in the first place, and what the official install guide is getting wrong. Please honestly read though the official one and mine and see the difference in how they read for a completely new user and how I try to take into account their existing OS and hardware, rather than leading them on a wild chase. If the official install guide can be updated to be reasonable for new users, than I will happily edit this page to more-or-less directly say just follow [link to the official guide]

**Comment by Head-on-a-Stick** [comment]
> I really appreciate this well thought out and eloquently worded feedback. 

You're welcome :-)

> hurtful 

Oh dear, poor you. Would you like a tissue to dry your eyes?

>contribute to the guide instead

The only guide people need is the official version. Please link to that instead.

> for a completely new user

Arch Linux is aimed at *competent* users. New users are expected to do their research.

**Comment by VegaDeftwing** [comment]
> Oh dear, poor you. Would you like a tissue to dry your eyes?

Yunno, it's disregard for the person across the series of tubes like this that give's Arch a bad reputation. We should all treat one another with respect.

> Arch Linux is aimed at competent users. New users are expected to do their research.

Sure, that doesn't mean we should make it hard or confusing for them to do so. We don't expect new users to write a bootloader from scratch or lean x86_64 assembly. We shouldn't expect a new user to fully understand - or even be able to understand at first - all the differences between UEFI and BIOS, x11 and wayland, or ext4 and NTFS. If you expect everyone to read every page on the wiki before installation, nobody will use Arch. What you're doing is gatekeeping.

**Comment by Head-on-a-Stick** [comment]
> Yunno, it's disregard for the person across the series of tubes like this that give's Arch a bad reputation. 

And it's Arch's "bad reputation" that keeps the idiots and help vampires away. Thank goodness for that.

> We should all treat one another with respect.

Then stop disrespecting the Arch community by putting up crap "guides" on your website.

> If you expect everyone to read every page on the wiki before installation, nobody will use Arch. What you're doing is gatekeeping.

I expect new users to follow the links provided in the installation guide to find the information they need. I don't think that's unreasonable. I regularly provide clarifications and explanations over at the forums, as do many other members of the community. 

There used to be a "beginner's" version of the installation guide[0] but the ArchWiki maintainers deemed it superfluous. I had nothing to do with that decision. The official guide is maintained by the Arch developers themselves so I'm not going to engage in your discussions on that page. I'll be happy to discuss your points on the forums though. I've already posted about this PR there as it happens :-D

[0] https://wiki.archlinux.org/title/User:Alad/Beginners%27_guide

**Comment by VegaDeftwing** [comment]
> I've already posted about this PR there as it happens :-D

Have a link?

**Comment by Rovoska** [comment]
> Oh dear, poor you. Would you like a tissue to dry your eyes?
No wonder Arch is a backwater OS when it’s evangelized by children

**Comment by VegaDeftwing** [comment]
Irony knows no bounds https://github.com/Head-on-a-Stick/SharpBang/blob/master/code-of-conduct.md

**Comment by CodeSteele** [comment]
whatdidi

**Comment by Head-on-a-Stick** [comment]
> Have a link?

https://bbs.archlinux.org/viewtopic.php?pid=2012076#p2012076

It's in a members-only section though so you'll have to log in to view it.

> No wonder Arch is a backwater OS when it’s evangelized by children

At what point have I "evangelized" [sic] Arch?

For the record: I couldn't give a crap who uses Arch or how popular it is and I find people who do care about such things to be weird.

> Irony knows no bounds https://github.com/Head-on-a-Stick/SharpBang/blob/master/code-of-conduct.md

This isn't the SharpBang repository. If you open an issue there rest assured that I will be as nice to you as I can stomach.

**Comment by Silvea12** [comment]
> At what point have I "evangelized" [sic] Arch?
See: "As a regular on the Arch forums."

Acting like a child because someone's guide is outdated instead of helping improve it is what gives a lot of arch users a bad name. Stop fucking it up for the rest of us.

**Comment by Head-on-a-Stick** [comment]
> > At what point have I "evangelized" [sic] Arch?
> 
> See: "As a regular on the Arch forums"

I don't see how that follows but whatever.

> Stop fucking it up for the rest of us.

Anybody who follows the "guide" under discussion will not be allowed to seek assistance at the Arch forums[1]. So the author really is "fucking it up" for those people.

[1] https://bbs.archlinux.org/viewtopic.php?id=130309

**Comment by VegaDeftwing** [comment]
> Anybody who follows the "guide" under discussion will not be allowed to seek assistance at the Arch forums[1]. So the author really is "fucking it up" for those people.
> https://bbs.archlinux.org/viewtopic.php?id=130309

Hate to tell ya, but this is an issue with the entire forums, not my guide. This is some of the lest welcoming, gate-keeper-y garbage I have ever read and makes me embarrassed to be an ArchLinux user. I can promise you a healthy majority of Arch Linux installations were done using a mix of the official install guide, YouTube videos, and extensive googling - some of which may have resulted in my guide. If the implication is that only the most pure of pure Arch Linux installs that were done without ever leaving https://wiki.archlinux.org/ are valid then that is just outright toxic and I would hope the real, helpful Arch Linux community I know and respect would call it out.

**Comment by SaphireLattice** [comment]
> Anybody who follows the "guide" under discussion will not be allowed to seek assistance at the Arch forums[[1]](https://bbs.archlinux.org/viewtopic.php?id=130309). So the author really is "fucking it up" for those people.

Well, that's quite a lovely link you have referenced. By the way, [GitHub markdown](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links) does allow embedding of links, you don't have to do HN style footnotes.

Anyways, that single forum topic/post is making me rapidly reconsider my 5 years of "diy" Arch install and to switch away to something nice. Manjaro, NixOS or maybe Alpine. Too bad I have missed this back then when I was considering the distro, due to never caring about forums of any kind.

**Comment by Head-on-a-Stick** [comment]
Well it's right there:
 >Installation Guide
> The guide to Arch Linux installation and setup. Support requires you followed this to get Arch Linux on your system.

And if it makes you feel any better one of the forum moderators has just officially warned me about my tone in this PR. Not that I could give a crap...

**Comment by Head-on-a-Stick** [comment]
> By the way, [GitHub markdown](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links) does allow embedding of links, you don't have to do HN style footnotes.

Thanks, I forgot about that.

> that single forum topic/post is making me rapidly reconsider my 5 years of "diy" Arch install and to switch away to something nice. Manjaro, NixOS or maybe Alpine.

Oh no, that's terrible. Guess I'll need a tissue now for my eyes...

I do recommend Alpine though, it's very good, much more "KISS" than Arch.

**Comment by yattaro** [comment]
> And if it makes you feel any better one of the forum moderators has just officially warned me about my tone in this PR. Not that I could give a crap...

Well yeah, it's one thing to provide constructive criticism about why you think this guide is inappropriate or otherwise redundant.  It's another to open discussion by directly insulting the author and their work simply because you don't agree with it without going into further detail.  I can imagine said mods probably agree with this.

**Comment by IntelMiner** [comment]
Disappointed to see Arch is filled with such shit people, it's a distribution with a lot of promise

**Pull request closed without merging**
